// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxBwH0LUT8HLP8s8d87hJpCk7Qs1GKw4c',
    appId: '1:701479392314:web:accb2fb7478bad1a495103',
    messagingSenderId: '701479392314',
    projectId: 'prepify-3b8b4',
    authDomain: 'prepify-3b8b4.firebaseapp.com',
    storageBucket: 'prepify-3b8b4.firebasestorage.app',
    measurementId: 'G-TCC1S7ZDM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKv6_ZzsU9JBXoCuDK_CYUXadbj47jCg',
    appId: '1:701479392314:android:e8375c0aba8763d1495103',
    messagingSenderId: '701479392314',
    projectId: 'prepify-3b8b4',
    storageBucket: 'prepify-3b8b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5nOScGw2_-3U3fRpzAkO7NCjDlNfWk8',
    appId: '1:701479392314:ios:5b88e7846fd10a6d495103',
    messagingSenderId: '701479392314',
    projectId: 'prepify-3b8b4',
    storageBucket: 'prepify-3b8b4.firebasestorage.app',
    iosClientId: '701479392314-5vgurdcd9b4q9doprdiqbattu9lmc9sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.prepify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg5nOScGw2_-3U3fRpzAkO7NCjDlNfWk8',
    appId: '1:701479392314:ios:5b88e7846fd10a6d495103',
    messagingSenderId: '701479392314',
    projectId: 'prepify-3b8b4',
    storageBucket: 'prepify-3b8b4.firebasestorage.app',
    iosClientId: '701479392314-5vgurdcd9b4q9doprdiqbattu9lmc9sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.prepify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxBwH0LUT8HLP8s8d87hJpCk7Qs1GKw4c',
    appId: '1:701479392314:web:9dd1bfed75678f21495103',
    messagingSenderId: '701479392314',
    projectId: 'prepify-3b8b4',
    authDomain: 'prepify-3b8b4.firebaseapp.com',
    storageBucket: 'prepify-3b8b4.firebasestorage.app',
    measurementId: 'G-V6HFRREC1D',
  );

}